import logging
import json
import os
from datetime import datetime
from dotenv import load_dotenv
from livekit.agents import (
    Agent,
    AgentSession,
    JobContext,
    JobProcess,
    MetricsCollectedEvent,
    RoomInputOptions,
    WorkerOptions,
    cli,
    metrics,
    tokenize,
    function_tool,
    RunContext
)
from livekit.plugins import murf, silero, google, deepgram, noise_cancellation
from livekit.plugins.turn_detector.multilingual import MultilingualModel

logger = logging.getLogger("agent")

load_dotenv(".env.local")

# --- DAY 3: WELLNESS COMPANION LOGIC ---

LOG_FILE = "wellness_log.json"

def get_last_checkin():
    """Reads the JSON file and returns the last entry if it exists."""
    if not os.path.exists(LOG_FILE):
        return None
    try:
        with open(LOG_FILE, "r") as f:
            data = json.load(f)
            if data and isinstance(data, list):
                return data[-1] # Return the last item in the list
    except Exception as e:
        logger.error(f"Error reading history: {e}")
    return None

class Assistant(Agent):
    def __init__(self) -> None:
        # 1. LOAD MEMORY: Check if we have talked before
        last_entry = get_last_checkin()
        
        # 2. CONSTRUCT CONTEXT: Create dynamic instructions based on history
        base_instructions = (
            "You are a supportive, grounded Health & Wellness Companion. "
            "Your goal is to do a daily check-in with the user. "
            "Follow this flow:\n"
            "1. Ask about their Mood and Energy levels.\n"
            "2. Ask for 1-3 simple, realistic goals/intentions for today.\n"
            "3. Offer ONE small, grounded piece of non-medical advice (e.g., 'take a walk', 'drink water').\n"
            "4. Recap what they said to confirm.\n"
            "5. Call the 'log_wellness_checkin' tool to save the entry.\n\n"
            "IMPORTANT: Do not give medical diagnosis or advice. Keep it casual and supportive."
        )

        # If we have history, add it to the brain!
        if last_entry:
            context_string = (
                f"\n\nCONTEXT FROM LAST SESSION ({last_entry['timestamp']}):\n"
                f"User felt: {last_entry['mood']}\n"
                f"Their goal was: {last_entry['objectives']}\n"
                "Start the conversation by welcoming them back and briefly referencing this past state "
                "(e.g., 'Last time you were feeling... how are you today?')."
            )
        else:
            context_string = "\n\nThis is your first meeting with the user. Introduce yourself warmly."

        super().__init__(
            instructions=base_instructions + context_string,
        )

    # --- THE TOOL TO SAVE THE MEMORY ---
    @function_tool
    async def log_wellness_checkin(
        self, 
        context: RunContext, 
        mood: str, 
        energy_level: str, 
        objectives: str, 
        summary: str
    ):
        """
        Call this tool at the END of the check-in to save the data.
        
        Args:
            mood: The user's self-reported mood (e.g., Happy, Stressed, Tired)
            energy_level: Self-reported energy (High, Low, Medium)
            objectives: The 1-3 goals the user mentioned.
            summary: A 1-sentence summary of the check-in generated by you.
        """
        
        new_entry = {
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "mood": mood,
            "energy": energy_level,
            "objectives": objectives,
            "summary": summary
        }
        
        # Read existing data
        history = []
        if os.path.exists(LOG_FILE):
            try:
                with open(LOG_FILE, "r") as f:
                    history = json.load(f)
            except:
                history = []

        # Add new entry
        history.append(new_entry)

        # Save back to file
        with open(LOG_FILE, "w") as f:
            json.dump(history, f, indent=2)

        print(f"💚 WELLNESS LOG SAVED: {new_entry}")
        return "I've logged your check-in for today. Take care!"


def prewarm(proc: JobProcess):
    proc.userdata["vad"] = silero.VAD.load()


async def entrypoint(ctx: JobContext):
    ctx.log_context_fields = {
        "room": ctx.room.name,
    }

    session = AgentSession(
        stt=deepgram.STT(model="nova-3"),
        llm=google.LLM(model="gemini-2.5-flash"),
        tts=murf.TTS(
                voice="en-US-matthew", 
                style="Conversation", 
                tokenizer=tokenize.basic.SentenceTokenizer(min_sentence_len=2),
                text_pacing=True
            ),
        turn_detection=MultilingualModel(),
        vad=ctx.proc.userdata["vad"],
        preemptive_generation=True,
    )

    usage_collector = metrics.UsageCollector()

    @session.on("metrics_collected")
    def _on_metrics_collected(ev: MetricsCollectedEvent):
        metrics.log_metrics(ev.metrics)
        usage_collector.collect(ev.metrics)

    async def log_usage():
        summary = usage_collector.get_summary()
        logger.info(f"Usage: {summary}")

    ctx.add_shutdown_callback(log_usage)

    await session.start(
        agent=Assistant(),
        room=ctx.room,
        room_input_options=RoomInputOptions(
            noise_cancellation=noise_cancellation.BVC(),
        ),
    )

    await ctx.connect()


if __name__ == "__main__":
    cli.run_app(WorkerOptions(entrypoint_fnc=entrypoint, prewarm_fnc=prewarm))